site_name: Jacob AI Book
site_description: "Jacob AI学习笔记"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2023-9999 Jacob Xi"

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"
  - 'AI大模型应用':
    - '1 大模型的理论与技术的演进' : 'chap1_ba/1intro.md'
    - '2 大模型开发基础：OpenAIEmbedding': 'chap1_ba/2embedding_openai.md'
    - '3 大模型实战--OpenAI开发': 'chap1_ba/3OpenaiModels.md'
    - '4 基于 ChatGPT 开发智能翻译助手': 'chap1_ba/4chatgpt_translate.md'
    - '5 产品经理的 5 个 AI 知识点：LLM、Agent、RAG、向量数据库、知识图谱': 'chap1_ba/5AI_PM.md'
  - 'AWS AI 应用':
    - '1 AWS AI 词汇表': 'chap2_aws/1aws_term.md'
    - '2 使用 LangChain搭建基于Amazon DynamoDB 的大语言模型应用': 'chap2_aws/2langchain_dynamodb.md'
    - '3 Amazon Bedrock 简介': 'chap2_aws/3AmazonBedrock.md'
    - '4 低代码机器学习': 'chap2_aws/4ML.md'
  - 'Prompt Engineering':
    - '1 Prompts & Use ChatGPT as a Powerful Tool for Programming': 'chap3_prompt/1prompt_code.md'
    - '2 11个顶级设计案例': 'chap3_prompt/2prompt_design.md'
  - 'Python GPT':
    - 'Creating an automated meeting minutes generator with Whisper and GPT-4' : 'chap4_python/1Meeting_minutes.md'
    - 'chatGPT API basics.': 'chap4_python/2API_Basic.md' 
  - 'Python GPT':
    - 'Creating an automated meeting minutes generator with Whisper and GPT-4' : 'chap4_python/1Meeting_minutes.md'
    - 'chatGPT API basics.': 'chap4_python/2API_Basic.md' 
  - 'AI基础学习':
    - '1 AI 简介' : 'chap2024_zh/1intro.md'
    - '2 Prompt Engineering，提示工程' : 'chap2024_zh/2Prompt.md'
    - '3 AI 编程简介' : 'chap2024_zh/3prommaming.md'
    - '4 OpenAI 的 Function Calling' : 'chap2024_zh/4assistantapi.md'
    - '5 RAG和Embeddings' : 'chap2024_zh/5rag.md'
  - 'Deepseek 模型':
    - '1 DeepSeek 模型介绍': 'dp1/1dp1_model.md'
  - 'Agent 学习':
    - '1 AI Agents入门教程之概述': 'chap5_agents/1agant_intro.md'
    - '2 AI Agents入门教程之从零开始构建Agent': 'chap5_agents/2agent_buildout.md'
    - '3 AI Agents入门教程之代理框架介绍': 'chap5_agents/3agent_frameworks.md'
  - 'MCP 学习':
    - '1 MCP 介绍': 'chap6_mcp/1mcp_intro.md'
    - '2 代码讲透MCP原理': 'chap6_mcp/1mcp_code.md'

repo_url: https://github.com/Chao-Xi/jxaibook.git
repo_name: "jxaibook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'teal'
    accent: 'teal'
  i18n:
    prev: 'Previous'
    next: 'Next'